### ISSUE TITLE
Cannot select any accounts. I already allowed it in the privacy settings

### ISSUE THREAD

**Issue by lucalauria98** [kzaremski/apple-notes-exporter#6]
<img width="582" alt="image" src="https://github.com/kzaremski/apple-notes-exporter/assets/74868798/1b846d35-e86e-4652-b6cc-e5d840d40c0d">

**Comment by kzaremski** [comment]
Thanks for opening this issue.

It seems that when notes are stored in IMAP/email accounts, they are identified as IMAPNote(s) instead of ICNote(s), and the same goes for the folders, accounts, and attachments. I made the logic that identifies the type of item more tolerant in the linked commit.

I was able to reproduce your exact issue, where it gets stuck querying an account (whose name is just the x-coredata uri), and my linked commit fixed the issue -- to be released in v0.4 build 3 shortly.
